### ISSUE TITLE
Adding custom header to single request

### ISSUE THREAD

**Issue by JuliusKoronci** [cantierecreativo/redux-bees#6]
Hi,
Is there an options to add a custom header to a single endpoint only. For example my login expects a POST request with content-type application/x-www-form-urlencoded but all other posts are expecting json

Thanks

**Comment by stefanoverna** [comment]
nope.. but a PR would be welcome :)

**Comment by MahmoudAlyuDeen** [comment]
@JuliusKoronci Why not do it dynamically?

```
export const getFormEncodedApi = () => buildApi(apiEndpoints, getFormEncodedConfig());

const getFormEncodedConfig = () => ({

   baseUrl: baseApiUrl,

   configureHeaders(headers) {
      return {
         ...headers,
         "Content-Type": "application/x-www-form-urlencoded",
      };
   }

});
```

Then you can use it like this:

```
getFormEncodedApi().login(...body);
```

**Comment by MrLeebo** [comment]
I think it is definitely worth it to be able to pass headers per a single request. The value of the header won't always be known in advance and may be specific to that request. For PII (Personally Identifiable Information), it is recommended to NOT include filter parameters that might contain PII in the URL's query string, because it is so difficult to account for all of the places where that URL will get logged. For GET requests, you can use a custom header as an alternative. So for a hypothetical API storing business contracts that can be searched via Tax ID (which is PII) instead of:

```
GET /api/contracts?taxId=1234567890
```

You send:

```
GET /api/contracts
X-TAX-ID: 1234567890
```

https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#79-pii-parameters

Needing to dynamically build the endpoint for each request and then save it in component/redux state (so that you can query on the endpoint later) is a really awkward workaround for this.

**Comment by GuyPaddock** [comment]
@JuliusKoronci Why did you close this issue?

I have a similar use case for this. Right now I'm doing this:
```jsx
  static build(baseUrl, headerContext) {
    const config = {
      baseUrl: baseUrl,
      configureHeaders(headers) {
        return {
          ...headers,
          ...headerContext.getAdditionalHeaders()
        }
      }
    };

    return buildApi(apiEndpoints, config);
  }
```

So that I can provide an anonymous object instance at API construction time that has access to mutable state:
```jsx
  constructor(props) {
    super(props);

    const outerThis = this;

    this.requestHeaders = {};
    this.headerContext  = {
      getAdditionalHeaders() {
        return outerThis.requestHeaders;
      }
    };

    this.api = MyApi.build(props.baseUrl, this.headerContext);
  }
```

Then before a request that needs, for example, a CSRF token:
```jsx
        Promise.resolve()
          .then(() => dispatch(this.startLoading()))
          .then(() =>
            MyApi.getCsrfToken(this.api, getState())
              .then((csrfToken) => {
                this.requestHeaders['X-CSRF-Token'] = csrfToken;
              })
          )
          .then(dispatch(this.api.someRequest())
          .then((result) => /* do something with the result here */)
          .catch((error) => console.error(error))
          .finally(() => dispatch(this.finishLoading()));
```
